name: getx_boilerplate
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter_native_splash: ^2.3.10
  flutter:
    sdk: flutter
  new_version_plus: ^0.0.11


dev_dependencies:
  flutter_lints: 3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

